Repository misterpeddy/hands-down, pull requests merged in 2020-04, with the labels that each got.

#46 Improves the notification system
  public/assets/blob.mp3
  public/assets/doNotTouch.png
  public/assets/stop-it-get-some-help.mp3
  public/js/notify.js
  public/js/ui.js
Labels: Priority: High, Status: In Review :detective:, Type: Enhancement :bulb:

#22 Fixes the prototype pollution vulnerability in minimist
  package-lock.json
  package.json
Labels: Priority: Medium, Status: Review Needed :passport_control:, Type: Vulnerability :warning:

#47 Adds LightHouse CI
  .github/lighthouserc.json
  .github/workflows/lighthouse.yml
  README.md
Labels: Priority: Critical, Type: Maintenance :construction:

#59 Use VisibilityChange API
  client/components/draw.js
  client/main.js
Labels: Priority: Critical
